name: cool-stuff

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show head_ref and secret
        run: |
          echo "PR: ${{ github.head_ref }}"
          echo "Notes: ${{ secrets.notes_programmers }}"
